name: 'Build and Deploy to GHCR'

on:
  push:
  pull_request:
    branches:
      - "main"

env:
  CR_PAT: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-publish-image:
    name: Build and Publish Docker image
    runs-on: ubuntu-latest
    env:
      working-directory: ./crush
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Build docker image
        run: docker build -t crush -p 42002:42002 .

      - name: Docker login
        run: echo $CR_PAT | docker login ghcr.io -u miho73 --password-stdin

      - name: Push image
        run: docker push ghcr.io/miho73/crush:latest
