name: 'Build and Deploy to GHCR'

on:
  workflow_dispatch:
#  push:
#  pull_request:
#    branches:
#      - "main"

env:
  CR_PAT: ${{ secrets.GITHUB_TOKEN }}
  SHA: ${{ github.sha }}

jobs:
  build-publish-image:
    name: Build and Publish Docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: miho73
          password: ${{ CR_PAT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Push image
        uses: docker/build-push-action@v6
        with:
          context: ./crush
          file: ./crush/Dockerfile
          push: true
          build-args: APP_COMMIT=${{SHA}}
          tags: |
            ghcr.io/miho73/crush:${{SHA}}
            ghcr.io/miho73/crush:latest
